name: Dependency Updates (Dependabot Auto-PR)

on:
  schedule:
    # Run every day at 05:00 UTC to check for dependency updates
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (security check)
        run: npm audit --audit-level=moderate

      - name: Run outdated check
        run: npm outdated || true

      - name: Update dependencies
        run: |
          npm update --save
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b dependency-updates-$(date +%Y%m%d)
          git add package*.json
          git commit -m "chore(deps): automated dependency update"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🔄 Automated Dependency Update"
          body: |
            This PR updates project dependencies to their latest compatible versions.
            - Automatically generated by GitHub Actions
            - Please review before merging
          branch: dependency-updates-$(date +%Y%m%d)
          base: main
