name: Publish docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Ensure public exists
        run: |
          if [ -f run.js ]; then node run.js || true; fi
          ls -la public || true

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
s