name: Draft Release Notes

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
