name: Scheduled Scrape & Commit

on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC (adjust if needed)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Run scraper
        run: node run.js

      - name: Commit generated public/ output if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update scraped data [ci skip]" || true
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
